# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: windows-latest

steps:
- powershell: |
    $teste1 = $env:DEV_TESTE123
    echo "##vso[task.setvariable variable=TesteDEVMODE;isOutput=true]$teste1"
  name: BuildVariable
  displayName: 'Set Environment Variables'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      dir env:
      
- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)\script_teste.ps1'
  # env:
  #   DEVMODE: $(DEVMODE)

